export const format = {
  width: 2000,
  height: 2000,
};

export const rarities = [
  {
    BACKGROUND: {
      Types: [
        "Blue sky",
        "Color mountain",
        "Pastel mountain",
        "Trippy mashroom",
      ],
    },
    BACKGEAR: {
      Types: [
        "Bapack ocopus",
        "Exoskeleton",
        "Katana",
        "Purple phantom spirit",
        "Skulls",
      ],
    },
    BASE: {
      Types: ["base body"],
    },
    EYES: {
      Types: [
        "Black and rainbow eyes",
        "Boring eyes",
        "Bright shining eyes",
        "Fire eyes",
        "Heart Eyes",
        "Hypno eyes",
        "Money dollar eyes",
        "Plenty of psychedlic eyes",
        "Rollingstone eyes",
        "Skull eyes",
      ],
    },
    EYEWEAR: {
      Types: [
        "Glasses with spike",
        "Pixel type glasses",
        "Ski mask",
        "Steampunk glasses",
        "Tech glasses",
        "VR cask",
      ],
    },
    FRONTGEAR: {
      Types: [
        "20 Rainbow cross bag",
        "21 ice cream",
        "22 soda",
        "24 tie",
        "27 snake",
        "29 water pump",
        "31 painter palette",
        "52 sushi hait",
        "98 tatoo",
        "99 exoskeleton arms",
      ],
    },
    HAIR: {
      Types: [
        "Hair black",
        "Pony tail",
      ],
    },
    HEADGEAR: {
      Types: [
        "Bags on head",
        "beani hat",
        "Beanni head",
        "Berret head",
        "Black horns",
        "Brain head",
        "Bunny cask",
        "Beanni head",
        "Captain hat",
        "Dino head",
        "Fluo red horns",
        "Ink angel ring",
        "Japanese bandana",
        "Multicolor unicorn",
        "Skeleton hat",
      ],
    },
    MASK: {
      Types: [
        "Cat mask",
        "Glasses and mask",
        "Half robotic face",
        "Hat with deer horn",
        "Transformer cask",
      ],
    },
    MOUTH: {
      Types: [
        "Bandana",
        "Boring mouth",
        "Cigar",
        "covid mask",
        "Kaneki ken masK",
        "Cigar",
        "Bubble gum",
        "open with rainbow",
        "Oxygen mask",
        "Rainbow waterfall",
        "Smile",
        "Zombie mouth",
      ],
    },
    OUTFIT: {
      Types: [
        "15 BLACK",
        "38 puffer jacket",
        "44 samurai armor detailed black",
        "60 spike vest",
        "75 Classy Suit",
        "88 black oversized hoodie",
        "94 VEST",
        "Mini_154 black",
        "Oversize hoodie"
      ],
    },
  },
  {
    BACKGROUND: {
      Types: [
        "Blue sky",
        "Color mountain",
        "Pastel mountain",
        "Trippy mashroom",
      ],
    },
    BACKGEAR: {
      Types: [
        "Bapack ocopus",
        "Exoskeleton",
        "Katana",
        "Purple phantom spirit",
        "Skulls",
      ],
    },
    BASE: {
      Types: ["base body"],
    },
    EYES: {
      Types: [
        "Black and rainbow eyes",
        "Boring eyes",
        "Bright shining eyes",
        "Fire eyes",
        "Heart Eyes",
        "Hypno eyes",
        "Money dollar eyes",
        "Plenty of psychedlic eyes",
        "Rollingstone eyes",
        "Skull eyes",
      ],
    },
    EYEWEAR: {
      Types: [
        "Laser Visorblue",
      ],
    },
    FRONTGEAR: {
      Types: [
        "20 Rainbow cross bag",
        "21 ice cream",
        "22 soda",
        "24 tie",
        "27 snake",
        "29 water pump",
        "31 painter palette",
        "52 sushi hait",
        "98 tatoo",
        "99 exoskeleton arms",
      ],
    },
    HAIR: {
      Types: [
        "Basic hair blue",
        "Hair blue",
      ],
    },
    HEADGEAR: {
      Types: [
        "Bags on head",
        "beani hat",
        "Beanni head",
        "Berret head",
        "Black horns",
        "Brain head",
        "Bunny cask",
        "Beanni head",
        "Captain hat",
        "Dino head",
        "Fluo red horns",
        "Ink angel ring",
        "Japanese bandana",
        "Multicolor unicorn",
        "Skeleton hat",
      ],
    },
    MASK: {
      Types: [
        "Cat mask",
        "Glasses and mask",
        "Half robotic face",
        "Hat with deer horn",
        "Transformer cask",
      ],
    },
    MOUTH: {
      Types: [
        "Bandana",
        "Boring mouth",
        "Cigar",
        "covid mask",
        "Kaneki ken masK",
        "Cigar",
        "Bubble gum",
        "open with rainbow",
        "Oxygen mask",
        "Rainbow waterfall",
        "Smile",
        "Zombie mouth",
      ],
    },
    OUTFIT: {
      Types: [
        "12 BLUE",
        "18 Translucent skeleton light blue",
        "30 Hawaiian shirt",
        "88 blue oversized hoodie",
        "100 blue pastel skin",
        "111 Dragon suit",
        "139 scales basic",
        "DIAMOND",
        "Mini_151 blue"
      ],
    },
  },
  {
    BACKGROUND: {
      Types: [
        "Blue sky",
        "Color mountain",
        "Pastel mountain",
        "Trippy mashroom",
      ],
    },
    BACKGEAR: {
      Types: [
        "Bapack ocopus",
        "Exoskeleton",
        "Katana",
        "Purple phantom spirit",
        "Skulls",
      ],
    },
    BASE: {
      Types: ["base body"],
    },
    EYES: {
      Types: [
        "Black and rainbow eyes",
        "Boring eyes",
        "Bright shining eyes",
        "Fire eyes",
        "Heart Eyes",
        "Hypno eyes",
        "Money dollar eyes",
        "Plenty of psychedlic eyes",
        "Rollingstone eyes",
        "Skull eyes",
      ],
    },
    EYEWEAR: {
      Types: [
        "Glasses with spike",
        "Pixel type glasses",
        "Ski mask",
        "Steampunk glasses",
        "Tech glasses",
        "VR cask",
      ],
    },
    FRONTGEAR: {
      Types: [
        "20 Rainbow cross bag",
        "21 ice cream",
        "22 soda",
        "24 tie",
        "27 snake",
        "29 water pump",
        "31 painter palette",
        "52 sushi hait",
        "98 tatoo",
        "99 exoskeleton arms",
      ],
    },
    HAIR: {
      Types: [
        "Dreadlocks short"
      ],
    },
    HEADGEAR: {
      Types: [
        "Bags on head",
        "beani hat",
        "Beanni head",
        "Berret head",
        "Black horns",
        "Brain head",
        "Bunny cask",
        "Beanni head",
        "Captain hat",
        "Dino head",
        "Fluo red horns",
        "Ink angel ring",
        "Japanese bandana",
        "Multicolor unicorn",
        "Skeleton hat",
      ],
    },
    MASK: {
      Types: [
        "Cat mask",
        "Glasses and mask",
        "Half robotic face",
        "Hat with deer horn",
        "Transformer cask",
      ],
    },
    MOUTH: {
      Types: [
        "Bandana",
        "Boring mouth",
        "Cigar",
        "covid mask",
        "Kaneki ken masK",
        "Cigar",
        "Bubble gum",
        "open with rainbow",
        "Oxygen mask",
        "Rainbow waterfall",
        "Smile",
        "Zombie mouth",
      ],
    },
    OUTFIT: {
      Types: [
        "41 robotic suite",
        "55 Jacket and sweater",
        "101 skeleton suit",
        "123 Fur jacket",
        "133 fur coat",
        "143 zombie dragon",
        "Mini_155 skeleton psychedelic",
      ],
    },
  },
  {
    BACKGROUND: {
      Types: [
        "Blue sky",
        "Color mountain",
        "Pastel mountain",
        "Trippy mashroom",
      ],
    },
    BACKGEAR: {
      Types: [
        "Bapack ocopus",
        "Exoskeleton",
        "Katana",
        "Purple phantom spirit",
        "Skulls",
      ],
    },
    BASE: {
      Types: ["base body"],
    },
    EYES: {
      Types: [
        "Black and rainbow eyes",
        "Boring eyes",
        "Bright shining eyes",
        "Fire eyes",
        "Heart Eyes",
        "Hypno eyes",
        "Money dollar eyes",
        "Plenty of psychedlic eyes",
        "Rollingstone eyes",
        "Skull eyes",
      ],
    },
    EYEWEAR: {
      Types: [
        "Glasses with spike",
        "Pixel type glasses",
        "Ski mask",
        "Steampunk glasses",
        "Tech glasses",
        "VR cask",
      ],
    },
    FRONTGEAR: {
      Types: [
        "20 Rainbow cross bag",
        "21 ice cream",
        "22 soda",
        "24 tie",
        "27 snake",
        "29 water pump",
        "31 painter palette",
        "52 sushi hait",
        "98 tatoo",
        "99 exoskeleton arms",
      ],
    },
    HAIR: {
      Types: [
        "Basic hair blue",
        "Basic hair green",
        "Basic hair pink ",
        "Hair blue",
        "Hair grey",
        "Hair black",
        "purple",
        "Medusa hair",
        "Pony tail",
      ],
    },
    HEADGEAR: {
      Types: [
        "Bags on head",
        "beani hat",
        "Beanni head",
        "Berret head",
        "Black horns",
        "Brain head",
        "Bunny cask",
        "Beanni head",
        "Captain hat",
        "Dino head",
        "Fluo red horns",
        "Ink angel ring",
        "Japanese bandana",
        "Multicolor unicorn",
        "Skeleton hat",
      ],
    },
    MASK: {
      Types: [
        "Cat mask",
        "Glasses and mask",
        "Half robotic face",
        "Hat with deer horn",
        "Transformer cask",
      ],
    },
    MOUTH: {
      Types: [
        "Bandana",
        "Boring mouth",
        "Cigar",
        "covid mask",
        "Kaneki ken masK",
        "Cigar",
        "Bubble gum",
        "open with rainbow",
        "Oxygen mask",
        "Rainbow waterfall",
        "Smile",
        "Zombie mouth",
      ],
    },
    OUTFIT: {
      Types: [
        "34 Torn hoodie",
        "40 kimono",
        "42 samurai armor detailed Gold",
        "59 pikachu suite",
        "88 yellow oversized hoodie",
        "GOLD",
        "GOLD2",
      ],
    },
  },
  {
    BACKGROUND: {
      Types: [
        "Blue sky",
        "Color mountain",
        "Pastel mountain",
        "Trippy mashroom",
      ],
    },
    BACKGEAR: {
      Types: [
        "Bapack ocopus",
        "Exoskeleton",
        "Katana",
        "Purple phantom spirit",
        "Skulls",
      ],
    },
    BASE: {
      Types: ["base body"],
    },
    EYES: {
      Types: [
        "Black and rainbow eyes",
        "Boring eyes",
        "Bright shining eyes",
        "Fire eyes",
        "Heart Eyes",
        "Hypno eyes",
        "Money dollar eyes",
        "Plenty of psychedlic eyes",
        "Rollingstone eyes",
        "Skull eyes",
      ],
    },
    EYEWEAR: {
      Types: [
        "Laser Visorgreen",
      ],
    },
    FRONTGEAR: {
      Types: [
        "20 Rainbow cross bag",
        "21 ice cream",
        "22 soda",
        "24 tie",
        "27 snake",
        "29 water pump",
        "31 painter palette",
        "52 sushi hait",
        "98 tatoo",
        "99 exoskeleton arms",
      ],
    },
    HAIR: {
      Types: [
        "Medusa hair",
      ],
    },
    HEADGEAR: {
      Types: [
        "Bags on head",
        "beani hat",
        "Beanni head",
        "Berret head",
        "Black horns",
        "Brain head",
        "Bunny cask",
        "Beanni head",
        "Captain hat",
        "Dino head",
        "Fluo red horns",
        "Ink angel ring",
        "Japanese bandana",
        "Multicolor unicorn",
        "Skeleton hat",
      ],
    },
    MASK: {
      Types: [
        "Cat mask",
        "Glasses and mask",
        "Half robotic face",
        "Hat with deer horn",
        "Transformer cask",
      ],
    },
    MOUTH: {
      Types: [
        "Bandana",
        "Boring mouth",
        "Cigar",
        "covid mask",
        "Kaneki ken masK",
        "Cigar",
        "Bubble gum",
        "open with rainbow",
        "Oxygen mask",
        "Rainbow waterfall",
        "Smile",
        "Zombie mouth",
      ],
    },
    OUTFIT: {
      Types: [
        "17 Light green wind",
        "35 Torn short T-shirt",
        "88 Green oversized hoodie",
        "141  ghost dragon",
        "GHOST DRAGON",
        "GREEN LEAF",
        "Mini_150 green leaf",
        "Mini_156 Light green wind",
        "SCALE BASIC",
        "ZOMBIE DRAGON",
      ],
    },
  },
  {
    BACKGROUND: {
      Types: [
        "Blue sky",
        "Color mountain",
        "Pastel mountain",
        "Trippy mashroom",
      ],
    },
    BACKGEAR: {
      Types: [
        "Bapack ocopus",
        "Exoskeleton",
        "Katana",
        "Purple phantom spirit",
        "Skulls",
      ],
    },
    BASE: {
      Types: ["base body"],
    },
    EYES: {
      Types: [
        "Black and rainbow eyes",
        "Boring eyes",
        "Bright shining eyes",
        "Fire eyes",
        "Heart Eyes",
        "Hypno eyes",
        "Money dollar eyes",
        "Plenty of psychedlic eyes",
        "Rollingstone eyes",
        "Skull eyes",
      ],
    },
    EYEWEAR: {
      Types: [
        "Glasses with spike",
        "Laser Visor purple",
        "Laser Visor red",
        "Laser Visorblue",
        "Laser Visorgreen",
        "Pixel type glasses",
        "Ski mask",
        "Steampunk glasses",
        "Tech glasses",
        "VR cask",
      ],
    },
    FRONTGEAR: {
      Types: [
        "20 Rainbow cross bag",
        "21 ice cream",
        "22 soda",
        "24 tie",
        "27 snake",
        "29 water pump",
        "31 painter palette",
        "52 sushi hait",
        "98 tatoo",
        "99 exoskeleton arms",
      ],
    },
    HAIR: {
      Types: [
        "Basic hair blue",
        "Basic hair green",
        "Basic hair pink ",
        "Hair blue",
        "Hair grey",
        "Hair black",
        "purple",
        "Medusa hair",
        "Pony tail",
      ],
    },
    HEADGEAR: {
      Types: [
        "Bags on head",
        "beani hat",
        "Beanni head",
        "Berret head",
        "Black horns",
        "Brain head",
        "Bunny cask",
        "Beanni head",
        "Captain hat",
        "Dino head",
        "Fluo red horns",
        "Ink angel ring",
        "Japanese bandana",
        "Multicolor unicorn",
        "Skeleton hat",
      ],
    },
    MASK: {
      Types: [
        "Cat mask",
        "Glasses and mask",
        "Half robotic face",
        "Hat with deer horn",
        "Transformer cask",
      ],
    },
    MOUTH: {
      Types: [
        "Bandana",
        "Boring mouth",
        "Cigar",
        "covid mask",
        "Kaneki ken masK",
        "Cigar",
        "Bubble gum",
        "open with rainbow",
        "Oxygen mask",
        "Rainbow waterfall",
        "Smile",
        "Zombie mouth",
      ],
    },
    OUTFIT: {
      Types: [
        "MULTICOLOR_RAINBOW",
      ],
    },
  },
  {
    BACKGROUND: {
      Types: [
        "Blue sky",
        "Color mountain",
        "Pastel mountain",
        "Trippy mashroom",
      ],
    },
    BACKGEAR: {
      Types: [
        "Bapack ocopus",
        "Exoskeleton",
        "Katana",
        "Purple phantom spirit",
        "Skulls",
      ],
    },
    BASE: {
      Types: ["base body"],
    },
    EYES: {
      Types: [
        "Black and rainbow eyes",
        "Boring eyes",
        "Bright shining eyes",
        "Fire eyes",
        "Heart Eyes",
        "Hypno eyes",
        "Money dollar eyes",
        "Plenty of psychedlic eyes",
        "Rollingstone eyes",
        "Skull eyes",
      ],
    },
    EYEWEAR: {
      Types: [
        "Glasses with spike",
        "Pixel type glasses",
        "Ski mask",
        "Steampunk glasses",
      ],
    },
    FRONTGEAR: {
      Types: [
        "20 Rainbow cross bag",
        "21 ice cream",
        "22 soda",
        "24 tie",
        "27 snake",
        "29 water pump",
        "31 painter palette",
        "52 sushi hait",
        "98 tatoo",
        "99 exoskeleton arms",
      ],
    },
    HAIR: {
      Types: [
        "Basic hair blue",
        "Basic hair green",
        "Basic hair pink ",
        "Hair blue",
        "Hair grey",
        "Hair black",
        "purple",
        "Medusa hair",
        "Pony tail",
      ],
    },
    HEADGEAR: {
      Types: [
        "Bags on head",
        "beani hat",
        "Beanni head",
        "Berret head",
        "Black horns",
        "Brain head",
        "Bunny cask",
        "Beanni head",
        "Captain hat",
        "Dino head",
        "Fluo red horns",
        "Ink angel ring",
        "Japanese bandana",
        "Multicolor unicorn",
        "Skeleton hat",
      ],
    },
    MASK: {
      Types: [
        "Cat mask",
        "Glasses and mask",
        "Half robotic face",
        "Hat with deer horn",
        "Transformer cask",
      ],
    },
    MOUTH: {
      Types: [
        "Bandana",
        "Boring mouth",
        "Cigar",
        "covid mask",
        "Kaneki ken masK",
        "Cigar",
        "Bubble gum",
        "open with rainbow",
        "Oxygen mask",
        "Rainbow waterfall",
        "Smile",
        "Zombie mouth",
      ],
    },
    OUTFIT: {
      Types: [
        "13 ORANGE",
        "32 Colored hoodie",
        "82 orange suit (jail)",
        "114 magikarp suit",
        "BROWN_EARTH",
        "Mini_152 orange",
      ],
    },
  },
  {
    BACKGROUND: {
      Types: [
        "Blue sky",
        "Color mountain",
        "Pastel mountain",
        "Trippy mashroom",
      ],
    },
    BACKGEAR: {
      Types: [
        "Bapack ocopus",
        "Exoskeleton",
        "Katana",
        "Purple phantom spirit",
        "Skulls",
      ],
    },
    BASE: {
      Types: ["base body"],
    },
    EYES: {
      Types: [
        "Black and rainbow eyes",
        "Boring eyes",
        "Bright shining eyes",
        "Fire eyes",
        "Heart Eyes",
        "Hypno eyes",
        "Money dollar eyes",
        "Plenty of psychedlic eyes",
        "Rollingstone eyes",
        "Skull eyes",
      ],
    },
    EYEWEAR: {
      Types: [
        "Laser Visor purple",
        "Laser Visor red",
        "Laser Visorblue",
        "Pixel type glasses",
        "Tech glasses",
      ],
    },
    FRONTGEAR: {
      Types: [
        "20 Rainbow cross bag",
        "21 ice cream",
        "22 soda",
        "24 tie",
        "27 snake",
        "29 water pump",
        "31 painter palette",
        "52 sushi hait",
        "98 tatoo",
        "99 exoskeleton arms",
      ],
    },
    HAIR: {
      Types: [
        "Basic hair pink ",
      ],
    },
    HEADGEAR: {
      Types: [
        "Bags on head",
        "beani hat",
        "Beanni head",
        "Berret head",
        "Black horns",
        "Brain head",
        "Bunny cask",
        "Beanni head",
        "Captain hat",
        "Dino head",
        "Fluo red horns",
        "Ink angel ring",
        "Japanese bandana",
        "Multicolor unicorn",
        "Skeleton hat",
      ],
    },
    MASK: {
      Types: [
        "Cat mask",
        "Glasses and mask",
        "Half robotic face",
        "Hat with deer horn",
        "Transformer cask",
      ],
    },
    MOUTH: {
      Types: [
        "Bandana",
        "Boring mouth",
        "Cigar",
        "covid mask",
        "Kaneki ken masK",
        "Cigar",
        "Bubble gum",
        "open with rainbow",
        "Oxygen mask",
        "Rainbow waterfall",
        "Smile",
        "Zombie mouth",
      ],
    },
    OUTFIT: {
      Types: [
        "88 pink oversized hoodie",
        "105 oversze hoodie with spike",
        "Mini_147 MULTICOLOR RAINBOW",
        "Mini_148 BROWN EARTH",
      ],
    },
  },
  {
    BACKGROUND: {
      Types: [
        "Blue sky",
        "Color mountain",
        "Pastel mountain",
        "Trippy mashroom",
      ],
    },
    BACKGEAR: {
      Types: [
        "Bapack ocopus",
        "Exoskeleton",
        "Katana",
        "Purple phantom spirit",
        "Skulls",
      ],
    },
    BASE: {
      Types: ["base body"],
    },
    EYES: {
      Types: [
        "Black and rainbow eyes",
        "Boring eyes",
        "Bright shining eyes",
        "Fire eyes",
        "Heart Eyes",
        "Hypno eyes",
        "Money dollar eyes",
        "Plenty of psychedlic eyes",
        "Rollingstone eyes",
        "Skull eyes",
      ],
    },
    EYEWEAR: {
      Types: [
        "Glasses with spike",
        "Pixel type glasses",
        "Ski mask",
        "Steampunk glasses",
        "Tech glasses",
        "VR cask",
      ],
    },
    FRONTGEAR: {
      Types: [
        "20 Rainbow cross bag",
        "21 ice cream",
        "22 soda",
        "24 tie",
        "27 snake",
        "29 water pump",
        "31 painter palette",
        "52 sushi hait",
        "98 tatoo",
        "99 exoskeleton arms",
      ],
    },
    HAIR: {
      Types: [
        "purple",
      ],
    },
    HEADGEAR: {
      Types: [
        "Bags on head",
        "beani hat",
        "Beanni head",
        "Berret head",
        "Black horns",
        "Brain head",
        "Bunny cask",
        "Beanni head",
        "Captain hat",
        "Dino head",
        "Fluo red horns",
        "Ink angel ring",
        "Japanese bandana",
        "Multicolor unicorn",
        "Skeleton hat",
      ],
    },
    MASK: {
      Types: [
        "Cat mask",
        "Glasses and mask",
        "Half robotic face",
        "Hat with deer horn",
        "Transformer cask",
      ],
    },
    MOUTH: {
      Types: [
        "Bandana",
        "Boring mouth",
        "Cigar",
        "covid mask",
        "Kaneki ken masK",
        "Cigar",
        "Bubble gum",
        "open with rainbow",
        "Oxygen mask",
        "Rainbow waterfall",
        "Smile",
        "Zombie mouth",
      ],
    },
    OUTFIT: {
      Types: [
        "14 PURPLE",
        "57 Patchwork jean jacket",
        "67 hoodie under jacket over",
        "68 formal short",
        "80 cosmonaut",
        "Mini_153 purple",
        "Outfit kinda gamer",
        "SHINING AURELION SOLE",
        "Shining aurelion sole-1",
      ],
    },
  },
  {
    BACKGROUND: {
      Types: [
        "Blue sky",
        "Color mountain",
        "Pastel mountain",
        "Trippy mashroom",
      ],
    },
    BACKGEAR: {
      Types: [
        "Bapack ocopus",
        "Exoskeleton",
        "Katana",
        "Purple phantom spirit",
        "Skulls",
      ],
    },
    BASE: {
      Types: ["base body"],
    },
    EYES: {
      Types: [
        "Black and rainbow eyes",
        "Boring eyes",
        "Bright shining eyes",
        "Fire eyes",
        "Heart Eyes",
        "Hypno eyes",
        "Money dollar eyes",
        "Plenty of psychedlic eyes",
        "Rollingstone eyes",
        "Skull eyes",
      ],
    },
    EYEWEAR: {
      Types: [
        "Laser Visor red",
      ],
    },
    FRONTGEAR: {
      Types: [
        "20 Rainbow cross bag",
        "21 ice cream",
        "22 soda",
        "24 tie",
        "27 snake",
        "29 water pump",
        "31 painter palette",
        "52 sushi hait",
        "98 tatoo",
        "99 exoskeleton arms",
      ],
    },
    HAIR: {
      Types: [
        "Basic hair blue",
        "Basic hair green",
        "Basic hair pink ",
        "Hair blue",
        "Hair grey",
        "Hair black",
        "purple",
        "Medusa hair",
        "Pony tail",
      ],
    },
    HEADGEAR: {
      Types: [
        "Bags on head",
        "beani hat",
        "Beanni head",
        "Berret head",
        "Black horns",
        "Brain head",
        "Bunny cask",
        "Beanni head",
        "Captain hat",
        "Dino head",
        "Fluo red horns",
        "Ink angel ring",
        "Japanese bandana",
        "Multicolor unicorn",
        "Skeleton hat",
      ],
    },
    MASK: {
      Types: [
        "Cat mask",
        "Glasses and mask",
        "Half robotic face",
        "Hat with deer horn",
        "Transformer cask",
      ],
    },
    MOUTH: {
      Types: [
        "Bandana",
        "Boring mouth",
        "Cigar",
        "covid mask",
        "Kaneki ken masK",
        "Cigar",
        "Bubble gum",
        "open with rainbow",
        "Oxygen mask",
        "Rainbow waterfall",
        "Smile",
        "Zombie mouth",
      ],
    },
    OUTFIT: {
      Types: [
        "28 king robe outfit",
        "36 Tokusatsu",
        "45 samurai armor detailed red",
        "88 red oversized hoodie",
        "Mini_149 RED FIRE",
        "RED_FIRE",
      ],
    },
  },
  {
    BACKGROUND: {
      Types: [
        "Blue sky",
        "Color mountain",
        "Pastel mountain",
        "Trippy mashroom",
      ],
    },
    BACKGEAR: {
      Types: [
        "Bapack ocopus",
        "Exoskeleton",
        "Katana",
        "Purple phantom spirit",
        "Skulls",
      ],
    },
    BASE: {
      Types: ["base body"],
    },
    EYES: {
      Types: [
        "Black and rainbow eyes",
        "Boring eyes",
        "Bright shining eyes",
        "Fire eyes",
        "Heart Eyes",
        "Hypno eyes",
        "Money dollar eyes",
        "Plenty of psychedlic eyes",
        "Rollingstone eyes",
        "Skull eyes",
      ],
    },
    EYEWEAR: {
      Types: [
        "Laser Visorblue",
        "Pixel type glasses",
        "Ski mask",
        "Steampunk glasses",
        "Tech glasses",
        "VR cask",
      ],
    },
    FRONTGEAR: {
      Types: [
        "20 Rainbow cross bag",
        "21 ice cream",
        "22 soda",
        "24 tie",
        "27 snake",
        "29 water pump",
        "31 painter palette",
        "52 sushi hait",
        "98 tatoo",
        "99 exoskeleton arms",
      ],
    },
    HAIR: {
      Types: [
        "Hair grey",
      ],
    },
    HEADGEAR: {
      Types: [
        "Bags on head",
        "beani hat",
        "Beanni head",
        "Berret head",
        "Black horns",
        "Brain head",
        "Bunny cask",
        "Beanni head",
        "Captain hat",
        "Dino head",
        "Fluo red horns",
        "Ink angel ring",
        "Japanese bandana",
        "Multicolor unicorn",
        "Skeleton hat",
      ],
    },
    MASK: {
      Types: [
        "Cat mask",
        "Glasses and mask",
        "Half robotic face",
        "Hat with deer horn",
        "Transformer cask",
      ],
    },
    MOUTH: {
      Types: [
        "Bandana",
        "Boring mouth",
        "Cigar",
        "covid mask",
        "Kaneki ken masK",
        "Cigar",
        "Bubble gum",
        "open with rainbow",
        "Oxygen mask",
        "Rainbow waterfall",
        "Smile",
        "Zombie mouth",
      ],
    },
    OUTFIT: {
      Types: [
        "16 Skeleton psychedelic",
        "19 translucent skeleton light grey",
        "37 Doctor",
        "39 cosmonaut",
        "54 overalls",
        "92 costume",
        "127 Demons hoodie",
        "140  robotic dragon",
        "Mini_146 DIAMOND",
        "Mini_157 translucent skeleton light blue",
        "ROBOTIC DRAGON",
      ],
    },
  },
];

export const supply = 2500;
export const startIndex = 501;
